-- Safetensors decomposer edge types. Emitted by the Safetensors model-decomp
-- pass orchestrator and its analysis passes. Source/target types reflect
-- the post-consolidation entity inventory (no bpe_token; word_form is the
-- canonical text-segment type).
INSERT INTO substrate.edge_type (code, category, source_type_id, target_type_id) VALUES
    -- Core architecture / weights metadata
    ('has_tensor_name',          'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_tokenizer_model',      'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_token_in_tokenizer',   'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form')),
    -- Per-tensor analysis surfaces
    ('has_weight_distribution',  'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_spectrum',             'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_eigenvalue_spectrum',  'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_sparsity_profile',     'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_activation_range',     'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_layer_norm_scale',     'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_codebook',             'model_derived', NULL, NULL),
    ('contains_codevector',      'model_derived', NULL, NULL),
    ('encodes_archetype',        'model_derived', NULL, NULL),
    ('has_layer_similarity',     'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor')),
    ('has_rope_freqs',           'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_rank_component',       'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_moe_routing',          'model_derived', NULL, NULL),
    ('has_embedding_position',   'model_derived', NULL, NULL),
    ('has_ffn_neuron',           'model_derived', NULL, NULL),
    ('has_logit_projection',     'model_derived', NULL, NULL),
    ('covers_lemma',             'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('has_vocab_coverage',       'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition'))
ON CONFLICT (code) DO NOTHING;
