-- 79 edge types in canonical order.
-- IDs 1..39 land in named partitions (tables/core/edge_structural.sql, edge_cross_lingual.sql,
-- edge_cross_modal.sql, edge_unicode.sql, edge_model.sql) per partition value lists.
-- IDs 40..79 land in edge_default (PARTITION OF DEFAULT). Once these stabilize,
-- a follow-up migration can move them into named partitions for index locality.
--
-- The 41 added types cover semantic content that the substrate cannot infer without:
--   WordNet pointer relations (40..63):  hypernym/hyponym/instance variants/holonyms/
--                                         meronyms/attribute/derivationally_related/antonym/
--                                         similar_to/also_see/verb_group/entailment/cause/
--                                         participle_of_verb/pertainym/six domain pointers/
--                                         has_frame
--   Wiktionary semantic relations (64..67): synonym/coordinate_term/derived/related
--   Wiktionary etymology templates (68..75): etym_inherited_from / etym_derived_from /
--                                             etym_borrowed_from / etym_cognate_with /
--                                             etym_calque_of / etym_mention / etym_link /
--                                             etym_etymon
-- (Note: hypernym/hyponym/meronym/antonym are shared codes — same edge_type used by both
--  WordNet (synset → synset) and Wiktionary (lemma → lemma); source/target type id rows
--  are descriptive only.)
INSERT INTO substrate.edge_type (code, category, source_type_id, target_type_id) VALUES
    ('has_sense',             'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('has_form',              'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'inflected_form')),
    ('has_lemma',             'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('has_morpheme',          'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form'),
        (SELECT id FROM substrate.entity_type WHERE code = 'morpheme')),
    ('has_gloss',             'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_example',           'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_name',              'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_text',              'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'tatoeba_sentence'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('inflection_of',         'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'inflected_form'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('has_etymology',         'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_pronunciation',     'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_hyphenation',       'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_wikidata',          'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('aligned_to_synset',     'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('translation_of',        'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('translation_link',      'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'tatoeba_sentence'),
        (SELECT id FROM substrate.entity_type WHERE code = 'tatoeba_sentence')),
    ('recording_of',          'cross_modal',
        (SELECT id FROM substrate.entity_type WHERE code = 'audio_recording'),
        (SELECT id FROM substrate.entity_type WHERE code = 'tatoeba_sentence')),
    ('has_contributor',       'cross_modal',
        (SELECT id FROM substrate.entity_type WHERE code = 'audio_recording'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('maps_to_lowercase',     'unicode',
        (SELECT id FROM substrate.entity_type WHERE code = 'codepoint'),
        (SELECT id FROM substrate.entity_type WHERE code = 'codepoint')),
    ('case_folds_to',         'unicode',
        (SELECT id FROM substrate.entity_type WHERE code = 'codepoint'),
        (SELECT id FROM substrate.entity_type WHERE code = 'codepoint')),
    ('has_collation_weight',  'unicode',
        (SELECT id FROM substrate.entity_type WHERE code = 'codepoint'),
        (SELECT id FROM substrate.entity_type WHERE code = 'collation_element')),
    ('in_model',              'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture')),
    ('in_layer',              'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture')),
    ('has_dtype',             'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_shape',             'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_hidden_size',       'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_num_layers',        'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_num_attention_heads','model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_vocab_size',        'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_token_string',      'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'bpe_token'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_token_id',          'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'bpe_token'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('in_vocabulary',         'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'bpe_token'),
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture')),
    ('co_occurrence',         'model_derived', NULL, NULL),
    ('macrolanguage_contains', 'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'language_name'),
        (SELECT id FROM substrate.entity_type WHERE code = 'language_name')),
    ('has_alternate_name',    'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'language_name'),
        (SELECT id FROM substrate.entity_type WHERE code = 'language_name')),
    ('superseded_by',         'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'language_name'),
        (SELECT id FROM substrate.entity_type WHERE code = 'language_name')),
    ('lexicalized_compound',  'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form'),
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form')),
    ('has_tensor',            'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor')),
    ('has_architecture_name', 'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    -- ── WordNet pointer relations (synset ↔ synset, except where noted) ────────
    ('hypernym',                'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('hyponym',                 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('instance_hypernym',       'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('instance_hyponym',        'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_holonym',          'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('substance_holonym',       'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('part_holonym',            'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_meronym',          'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('substance_meronym',       'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('part_meronym',            'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('attribute',               'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('derivationally_related',  'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('antonym',                 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('similar_to',              'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('also_see',                'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('verb_group',              'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('entailment',              'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('cause',                   'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('participle_of_verb',      'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('pertainym',               'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('domain_of_synset_topic',  'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_of_domain_topic',  'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('domain_of_synset_region', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_of_domain_region', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('domain_of_synset_usage',  'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_of_domain_usage',  'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('has_frame',               'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    -- ── Wiktionary semantic relations (lemma ↔ lemma) ────────────────────────
    ('synonym',                 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('coordinate_term',         'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('derived',                 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('related',                 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    -- ── Wiktionary etymology templates (wikt_sense ↔ lemma / text_composition) ─
    ('etym_inherited_from',     'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('etym_derived_from',       'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('etym_borrowed_from',      'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('etym_cognate_with',       'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('etym_calque_of',          'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('etym_mention',            'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('etym_link',               'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('etym_etymon',             'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'wikt_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    -- ── External-identifier bridge edges ──────────────────────────────────────
    -- Records source-system identifiers as substrate content (placement on an
    -- edge, not in the entity's identity hash). OMW joins via this edge to
    -- locate WordNet synsets by their authoring offset. has_frame already
    -- declared above among the WordNet pointer block.
    ('has_wordnet_offset',      'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition'));
