-- 79 edge types in canonical order.
-- IDs 1..39 land in named partitions (tables/core/edge_structural.sql, edge_cross_lingual.sql,
-- edge_cross_modal.sql, edge_unicode.sql, edge_model.sql) per partition value lists.
-- IDs 40..79 land in edge_default (PARTITION OF DEFAULT). Once these stabilize,
-- a follow-up migration can move them into named partitions for index locality.
--
-- The 41 added types cover semantic content that the substrate cannot infer without:
--   WordNet pointer relations (40..63):  hypernym/hyponym/instance variants/holonyms/
--                                         meronyms/attribute/derivationally_related/antonym/
--                                         similar_to/also_see/verb_group/entailment/cause/
--                                         participle_of_verb/pertainym/six domain pointers/
--                                         has_frame
--   Wiktionary semantic relations (64..67): synonym/coordinate_term/derived/related
--   Wiktionary etymology templates (68..75): etym_inherited_from / etym_derived_from /
--                                             etym_borrowed_from / etym_cognate_with /
--                                             etym_calque_of / etym_mention / etym_link /
--                                             etym_etymon
-- (Note: hypernym/hyponym/meronym/antonym are shared codes — same edge_type used by both
--  WordNet (synset → synset) and Wiktionary (lemma → lemma); source/target type id rows
--  are descriptive only.)
INSERT INTO substrate.edge_type (code, category, source_type_id, target_type_id) VALUES
    ('has_sense',             'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('has_form',              'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form')),
    ('has_lemma',             'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('has_morpheme',          'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form'),
        (SELECT id FROM substrate.entity_type WHERE code = 'morpheme')),
    ('has_gloss',             'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_example',           'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_name',              'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('inflection_of',         'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('has_etymology',         'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_pronunciation',     'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_hyphenation',       'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_wikidata',          'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('aligned_to_synset',     'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('translation_of',        'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('translation_link',      'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('recording_of',          'cross_modal',
        (SELECT id FROM substrate.entity_type WHERE code = 'audio_recording'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_contributor',       'cross_modal',
        (SELECT id FROM substrate.entity_type WHERE code = 'audio_recording'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('maps_to_lowercase',     'unicode',
        (SELECT id FROM substrate.entity_type WHERE code = 'codepoint'),
        (SELECT id FROM substrate.entity_type WHERE code = 'codepoint')),
    ('case_folds_to',         'unicode',
        (SELECT id FROM substrate.entity_type WHERE code = 'codepoint'),
        (SELECT id FROM substrate.entity_type WHERE code = 'codepoint')),
    ('has_collation_weight',  'unicode',
        (SELECT id FROM substrate.entity_type WHERE code = 'codepoint'),
        (SELECT id FROM substrate.entity_type WHERE code = 'collation_element')),
    ('in_model',              'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture')),
    ('in_layer',              'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture')),
    ('has_dtype',             'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_shape',             'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_hidden_size',       'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_num_layers',        'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_num_attention_heads','model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_vocab_size',        'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_token_id',          'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('in_vocabulary',         'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form'),
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture')),
    ('co_occurrence',         'model_derived', NULL, NULL),
    ('macrolanguage_contains', 'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'language_name'),
        (SELECT id FROM substrate.entity_type WHERE code = 'language_name')),
    ('has_alternate_name',    'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'language_name'),
        (SELECT id FROM substrate.entity_type WHERE code = 'language_name')),
    ('superseded_by',         'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'language_name'),
        (SELECT id FROM substrate.entity_type WHERE code = 'language_name')),
    ('lexicalized_compound',  'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form'),
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form')),
    ('has_tensor',            'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor')),
    ('has_architecture_name', 'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    -- ── WordNet pointer relations (synset ↔ synset, except where noted) ────────
    ('hypernym',                'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('hyponym',                 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('instance_hypernym',       'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('instance_hyponym',        'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_holonym',          'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('substance_holonym',       'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('part_holonym',            'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_meronym',          'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('substance_meronym',       'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('part_meronym',            'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('attribute',               'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('derivationally_related',  'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('antonym',                 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('similar_to',              'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('also_see',                'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('verb_group',              'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('entailment',              'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('cause',                   'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('participle_of_verb',      'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('pertainym',               'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('domain_of_synset_topic',  'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_of_domain_topic',  'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('domain_of_synset_region', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_of_domain_region', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('domain_of_synset_usage',  'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_of_domain_usage',  'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('has_frame',               'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    -- ── Wiktionary semantic relations (lemma ↔ lemma) ────────────────────────
    ('synonym',                 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('coordinate_term',         'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('derived',                 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('related',                 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    -- ── Etymology templates (lemma ↔ lemma / text_composition) ──────────
    -- Source-side is lemma (with provenance=wiktextract distinguishing
    -- Wiktionary-derived etymology from any other source).
    ('etym_inherited_from',     'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('etym_derived_from',       'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('etym_borrowed_from',      'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('etym_cognate_with',       'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('etym_calque_of',          'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('etym_mention',            'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('etym_link',               'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('etym_etymon',             'cross_lingual',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    -- ── External-identifier bridge edges ──────────────────────────────────────
    -- Records source-system identifiers as substrate content (placement on an
    -- edge, not in the entity's identity hash). OMW joins via this edge to
    -- locate WordNet synsets by their authoring offset. has_frame already
    -- declared above among the WordNet pointer block.
    ('has_wordnet_offset',      'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),

    -- ── Safetensors model-decomposition edges ───────────────────────────────
    -- Per-tensor metadata, tokenizer associations, weight-distribution
    -- analysis surfaces. Many are emitted by advanced passes; some target
    -- text_composition (metadata as text), some target tensor or word_form.
    ('has_tensor_name',          'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_tokenizer_model',      'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('has_token_in_tokenizer',   'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'model_architecture'),
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form')),
    ('has_weight_distribution',  'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'weight_distribution')),
    ('has_spectrum',             'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'svd_spectrum')),
    ('has_eigenvalue_spectrum',  'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'eigenvalue_spectrum')),
    ('has_sparsity_profile',     'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'sparsity_profile')),
    ('has_activation_range',     'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'activation_range')),
    ('has_layer_norm_scale',     'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'layer_norm_scale')),
    ('has_codebook',             'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'codec_codebook')),
    ('contains_codevector',      'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'codec_codebook'),
        (SELECT id FROM substrate.entity_type WHERE code = 'codec_codevector')),
    ('encodes_archetype',        'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'archetype')),
    ('has_layer_similarity',     'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'layer_similarity_pair')),
    ('has_rope_freqs',           'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'rope_freq_table')),
    ('has_rank_component',       'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'svd_rank_component')),
    ('has_moe_routing',          'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'moe_routing_profile')),
    ('has_embedding_position',   'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'embedding_position')),
    ('has_ffn_neuron',           'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'ffn_neuron')),
    ('has_logit_projection',     'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tensor'),
        (SELECT id FROM substrate.entity_type WHERE code = 'logit_projection')),
    ('covers_lemma',             'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_form'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('has_vocab_coverage',       'model_derived',
        (SELECT id FROM substrate.entity_type WHERE code = 'tokenizer_model'),
        (SELECT id FROM substrate.entity_type WHERE code = 'vocab_coverage_profile'));

-- ── semantic_weight tier ladder ───────────────────────────────────────
-- Default 1.0 (column default) covers tier-1 codes: structural and antonymy.
-- Lower tiers are explicit UPDATEs.
--
-- Tier 0.9 — meronymy and morphology
UPDATE substrate.edge_type SET semantic_weight = 0.9  WHERE code IN (
    'member_holonym', 'substance_holonym', 'part_holonym',
    'member_meronym', 'substance_meronym', 'part_meronym', 'has_morpheme');
-- Tier 0.85 — cross-lingual structural alignment
UPDATE substrate.edge_type SET semantic_weight = 0.85 WHERE code IN (
    'translation_of', 'aligned_to_synset', 'translation_link');
-- Tier 0.7 — linguistic specialty content (etymology, pronunciation, etc.)
UPDATE substrate.edge_type SET semantic_weight = 0.7  WHERE code IN (
    'has_etymology', 'has_pronunciation', 'has_hyphenation', 'has_wikidata');
-- Tier 0.6 — looser semantic relations
UPDATE substrate.edge_type SET semantic_weight = 0.6  WHERE code IN (
    'similar_to', 'also_see', 'verb_group', 'attribute', 'derivationally_related');
-- Tier 0.5 — weakest semantic claims
UPDATE substrate.edge_type SET semantic_weight = 0.5  WHERE code IN (
    'synonym', 'related', 'coordinate_term', 'derived');
