namespace Hartonomous.Decomposers.Safetensors;

public enum TensorRole
{
    Unknown,
    // Track 1 — wholesale embedding ingestion.
    TokenEmbedding,
    TokenTypeEmbedding,
    PositionEmbedding,
    PositionEmbedding2D,
    RopeFreq,
    VqCodebook,
    ObjectQuery,
    // Track 2 — transformation weights.
    AttentionQuery,
    AttentionKey,
    AttentionValue,
    AttentionOutput,
    CrossAttention,
    FfnGate,
    FfnUp,
    FfnDown,
    MoeRouter,
    MoeExpertGate,
    MoeExpertUp,
    MoeExpertDown,
    MoeSharedExpert,
    LogitHead,
    ClassHead,
    BboxHead,
    ConvKernel,
    DiffusionBlock,
    VaeBlock,
    ConformerLayer,
    AudioCodecEncoder,
    AudioCodecDecoder,
    VisionFeature,
    VisionProjection,
    ModalityProjection,
    LoraA,
    LoraB,
    // Reference-only (not decomposed into edges).
    LayerNorm,
    BatchNorm,
    RmsNorm,
    MelFilterbank,
    CodebookScale,
    Fp8Scale,
    AnchorGrid,
}
