-- substrate.sense INTENTIONALLY REMOVED.
--
-- This table was a surrogate-id holdover from before hash-as-PK. WordNet
-- sense_keys (e.g., "abandon%2:38:00::") are structured CONTENT — they
-- decompose into lemma_hash + synset_hash + lexname_id + lex_id, all of
-- which already live elsewhere in the substrate. A "word sense" is a
-- substrate.entity row of entity_type=word_sense (id 14, content-hashed
-- via BLAKE3 of the canonical tuple), not a varchar-coded reference row.
--
-- The lemma↔sense and sense↔synset relationships are edges (has_sense,
-- in_synset) with per-arena Glicko ratings via substrate.edge_significance.
-- Lexname classification is a junction (substrate.entity_lexname) on the
-- word_sense entity. POS classification reuses substrate.entity_pos.
--
-- Deleting this file from the seed include chain replaces the table
-- entirely; nothing FKs to substrate.sense.id since there are no longer
-- any junctions referencing sense_id.
SELECT 1; -- placeholder so this .sql file remains loadable if @included.
