-- Stage 0006: substrate.entity — single content-addressed table.
-- Per the unification refactor (docs/specs/text-decomposer-unification.md
-- Phase C), substrate.entity has a hash-only primary key. No LIST partition
-- by entity_type_id (classifications live on substrate.entity_classification
-- per migration 0025, not on the entity row).
-- @include schema/tables/core/entity.sql
