-- Stage 0014: monitor schema tables.
-- @include schema/tables/monitor/ingestion_progress.sql
-- @include schema/tables/monitor/phase_status.sql
-- @include schema/tables/monitor/error_log.sql
-- @include schema/tables/monitor/substrate_health.sql
-- @include schema/tables/monitor/inference_metrics.sql
-- @include schema/tables/monitor/session.sql
-- @include schema/tables/monitor/comparison_event.sql
-- @include schema/tables/monitor/significance_snapshot.sql
