-- Stage 0015: monitor procedures + dashboard views consumed by the CLI's
-- session, phase, and progress surfaces.
-- @include schema/procedures/monitor_create_session.sql
-- @include schema/procedures/monitor_close_session.sql
-- @include schema/procedures/monitor_archive_session.sql
-- @include schema/procedures/monitor_update_phase_status.sql
-- @include schema/procedures/monitor_report_progress.sql
-- @include schema/procedures/monitor_snapshot_health.sql
-- @include schema/views/substrate_dashboard.sql
-- @include schema/views/v_active_runs.sql
