-- 0018_wordnet_seed.up.sql
-- Edge types, semantic relation types, and lexname seed for Princeton WordNet 3.0.

-- Lexicographer file categories (45 rows from lexnames file).
INSERT INTO substrate.lexname (code) VALUES
    ('adj.all'), ('adj.pert'), ('adv.all'), ('noun.Tops'), ('noun.act'),
    ('noun.animal'), ('noun.artifact'), ('noun.attribute'), ('noun.body'),
    ('noun.cognition'), ('noun.communication'), ('noun.event'), ('noun.feeling'),
    ('noun.food'), ('noun.group'), ('noun.location'), ('noun.motive'),
    ('noun.object'), ('noun.person'), ('noun.phenomenon'), ('noun.plant'),
    ('noun.possession'), ('noun.process'), ('noun.quantity'), ('noun.relation'),
    ('noun.shape'), ('noun.state'), ('noun.substance'), ('noun.time'),
    ('verb.body'), ('verb.change'), ('verb.cognition'), ('verb.communication'),
    ('verb.competition'), ('verb.consumption'), ('verb.contact'), ('verb.creation'),
    ('verb.emotion'), ('verb.motion'), ('verb.perception'), ('verb.possession'),
    ('verb.social'), ('verb.stative'), ('verb.weather'), ('adj.ppl')
ON CONFLICT (code) DO NOTHING;

-- Semantic relation types (WordNet pointer vocabulary).
INSERT INTO substrate.semantic_relation_type (code) VALUES
    ('antonym'), ('hypernym'), ('instance_hypernym'), ('hyponym'), ('instance_hyponym'),
    ('member_holonym'), ('substance_holonym'), ('part_holonym'),
    ('member_meronym'), ('substance_meronym'), ('part_meronym'),
    ('attribute'), ('derivationally_related'),
    ('domain_of_synset_topic'), ('member_of_domain_topic'),
    ('domain_of_synset_region'), ('member_of_domain_region'),
    ('domain_of_synset_usage'), ('member_of_domain_usage'),
    ('entailment'), ('cause'), ('also_see'), ('verb_group'),
    ('similar_to'), ('participle_of_verb'), ('pertainym')
ON CONFLICT (code) DO NOTHING;

-- Edge types for WordNet semantic relations.
-- All semantic edges go synset→synset or word_sense→word_sense.
-- Using entity_type lookups for source/target constraints.
INSERT INTO substrate.edge_type (code, category, source_type_id, target_type_id) VALUES
    ('antonym', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'word_sense')),
    ('hypernym', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('instance_hypernym', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('hyponym', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('instance_hyponym', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_holonym', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('substance_holonym', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('part_holonym', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_meronym', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('substance_meronym', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('part_meronym', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('attribute', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('derivationally_related', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'word_sense')),
    ('domain_of_synset_topic', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_of_domain_topic', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('domain_of_synset_region', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_of_domain_region', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('domain_of_synset_usage', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('member_of_domain_usage', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('entailment', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('cause', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('also_see', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('verb_group', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('similar_to', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('participle_of_verb', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'word_sense')),
    ('pertainym', 'semantic',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'word_sense'))
ON CONFLICT (code) DO NOTHING;

-- Structural edge types for WordNet.
INSERT INTO substrate.edge_type (code, category, source_type_id, target_type_id) VALUES
    ('in_synset', 'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'synset')),
    ('has_word', 'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'synset'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('has_verb_frame', 'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition')),
    ('irregular_morphology', 'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma'),
        (SELECT id FROM substrate.entity_type WHERE code = 'lemma')),
    ('has_verb_example', 'structural',
        (SELECT id FROM substrate.entity_type WHERE code = 'word_sense'),
        (SELECT id FROM substrate.entity_type WHERE code = 'text_composition'))
ON CONFLICT (code) DO NOTHING;
