DROP FUNCTION IF EXISTS substrate.recall(BYTEA, INT, INT, DOUBLE PRECISION);
DROP FUNCTION IF EXISTS substrate.recall(BYTEA, INT, INT);
DROP FUNCTION IF EXISTS substrate.intersect(BYTEA[], INT, INT, DOUBLE PRECISION);
DROP FUNCTION IF EXISTS substrate.neighborhood(BYTEA, INT, DOUBLE PRECISION);
DROP FUNCTION IF EXISTS substrate.dist_4d(geometry, geometry);
