CREATE TABLE substrate.safetensor_observation (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observed_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    model_source_id         INT REFERENCES substrate.model_source(id),
    context_type_id         INT NOT NULL REFERENCES substrate.significance_context(id),
    attestation_type_id    INT NOT NULL REFERENCES substrate.attestation_type(id),
    edge_type_id            INT NOT NULL REFERENCES substrate.edge_type(id),
    edge_hash               substrate.hash_value NOT NULL,
    score                  DOUBLE PRECISION NOT NULL,
    weight                 DOUBLE PRECISION NOT NULL,
    -- Entity FK is application-enforced — substrate.entity is HASH-partitioned
    -- by hash_bits_0_51 and PG does not accept FKs to a non-unique single column.
    tensor_hash             substrate.hash_value,
    package_tensor_hash     substrate.hash_value,
    source_tensor_name      TEXT,
    primitive_code          TEXT,
    tuple_code              TEXT,
    slot_code               TEXT,
    modality_code           TEXT,
    layer_index             INT,
    head_index              INT,
    expert_index            INT,
    adapter_name            TEXT,
    fused_slice             TEXT
);

COMMENT ON TABLE substrate.safetensor_observation IS
    'Durable source/placement-aware safetensor evidence events. edge_significance remains the aggregate consensus; this ledger preserves which model package/tensor placement produced each observation for recomposition filters.';
