/*
 * gen_codepoint_hashes — emit BLAKE3 of the UTF-8 bytes of every Unicode
 * scalar value U+0000..U+10FFFF (skipping surrogates U+D800..U+DFFF).
 *
 * The substrate keys per-codepoint atoms by `hartonomous_blake3` of their
 * canonical UTF-8 bytes. `hartonomous_text_decompose` recomputes that on
 * the fly, but ingestion-time and PG-side queries benefit from a baked
 * lookup table indexed by codepoint. This generator emits:
 *
 *   lh_codepoint_hashes.h    — declares  extern const uint8_t
 *                              lh_codepoint_hash_bytes[1114112][32];
 *   lh_codepoint_hashes.c    — defines the table.
 *
 * Surrogate slots are filled with the all-zero hash (sentinel) since
 * U+D800..U+DFFF cannot be encoded as UTF-8 and are never atomized.
 *
 * No input file is required — the table is purely synthetic.
 *
 * Usage:
 *   gen_codepoint_hashes <out_dir>
 */

#include "lh_emit.h"

#include <blake3.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int utf8_encode(uint32_t cp, uint8_t *out)
{
    if (cp <= 0x7Fu) { out[0] = (uint8_t)cp; return 1; }
    if (cp <= 0x7FFu) {
        out[0] = (uint8_t)(0xC0u | (cp >> 6));
        out[1] = (uint8_t)(0x80u | (cp & 0x3Fu));
        return 2;
    }
    if (cp <= 0xFFFFu) {
        out[0] = (uint8_t)(0xE0u | (cp >> 12));
        out[1] = (uint8_t)(0x80u | ((cp >> 6) & 0x3Fu));
        out[2] = (uint8_t)(0x80u | (cp & 0x3Fu));
        return 3;
    }
    out[0] = (uint8_t)(0xF0u | (cp >> 18));
    out[1] = (uint8_t)(0x80u | ((cp >> 12) & 0x3Fu));
    out[2] = (uint8_t)(0x80u | ((cp >> 6) & 0x3Fu));
    out[3] = (uint8_t)(0x80u | (cp & 0x3Fu));
    return 4;
}

static int emit_header(const char *out_dir)
{
    lh_emit e;
    if (lh_emit_open_header(&e, out_dir, "lh_codepoint_hashes") != 0) {
        perror("open header");
        return -1;
    }
    lh_emit_printf(&e,
        "/* GENERATED by codegen/gen_codepoint_hashes. DO NOT EDIT. */\n"
        "\n"
        "#ifndef LH_CODEPOINT_HASHES_H\n"
        "#define LH_CODEPOINT_HASHES_H\n"
        "\n"
        "#include <stdint.h>\n"
        "\n"
        "#define LH_CODEPOINT_HASH_COUNT 0x110000u\n"
        "#define LH_CODEPOINT_HASH_LEN   32u\n"
        "\n"
        "/* Indexed by Unicode scalar value 0..0x10FFFF inclusive.\n"
        " * Surrogate slots (0xD800..0xDFFF) are all-zero. */\n"
        "extern const uint8_t lh_codepoint_hash_bytes[LH_CODEPOINT_HASH_COUNT][LH_CODEPOINT_HASH_LEN];\n"
        "\n"
        "#endif /* LH_CODEPOINT_HASHES_H */\n");
    return lh_emit_close(&e);
}

static int emit_source(const char *out_dir)
{
    lh_emit e;
    if (lh_emit_open_source(&e, out_dir, "lh_codepoint_hashes") != 0) {
        perror("open source");
        return -1;
    }
    lh_emit_printf(&e,
        "/* GENERATED by codegen/gen_codepoint_hashes. DO NOT EDIT. */\n"
        "\n"
        "#include \"lh_codepoint_hashes.h\"\n"
        "\n"
        "const uint8_t lh_codepoint_hash_bytes[LH_CODEPOINT_HASH_COUNT][LH_CODEPOINT_HASH_LEN] = {\n");

    uint8_t hash[32];
    uint8_t utf8[4];
    for (uint32_t cp = 0; cp < 0x110000u; cp++) {
        if (cp >= 0xD800u && cp <= 0xDFFFu) {
            memset(hash, 0, 32);
        } else {
            int n = utf8_encode(cp, utf8);
            blake3_hasher h;
            blake3_hasher_init(&h);
            blake3_hasher_update(&h, utf8, (size_t)n);
            blake3_hasher_finalize(&h, hash, 32);
        }
        lh_emit_printf(&e, "    /* U+%06X */ {", cp);
        for (int i = 0; i < 32; i++) {
            lh_emit_printf(&e, "0x%02x%s", hash[i], i == 31 ? "" : ",");
        }
        lh_emit_printf(&e, "}%s\n", cp == 0x10FFFFu ? "" : ",");
    }

    lh_emit_printf(&e, "};\n");
    return lh_emit_close(&e);
}

int main(int argc, char **argv)
{
    if (argc != 2) {
        fprintf(stderr, "usage: %s <out_dir>\n", argv[0]);
        return 2;
    }
    if (emit_header(argv[1]) != 0) return 1;
    if (emit_source(argv[1]) != 0) return 1;
    return 0;
}
