-- Stage 0003: substrate domains (hash_value, significance_*, ordinal, rle, code_value, tier).
-- @include schema/domains/hash_value.sql
-- @include schema/domains/significance_mu.sql
-- @include schema/domains/significance_sigma.sql
-- @include schema/domains/significance_volatility.sql
-- @include schema/domains/ordinal_position.sql
-- @include schema/domains/rle_count.sql
-- @include schema/domains/code_value.sql
-- @include schema/domains/tier_number.sql
