-- Stage 0005: 18 reference tables. FK-ordered: independents first, then
-- self-referencing, then FK-dependent.
--
-- substrate.sense was removed: WordNet sense_keys are content, not
-- bounded vocabulary. word_sense entities live in substrate.entity now,
-- content-hashed via BLAKE3 of (lemma_hash || synset_hash || lexname_id ||
-- lex_id), reachable via the has_sense / in_synset edges and classified
-- via the entity_lexname junction.
-- @include schema/tables/reference/entity_type.sql
-- @include schema/tables/reference/edge_role.sql
-- @include schema/tables/reference/physicality_type.sql
-- @include schema/tables/reference/significance_context.sql
-- @include schema/tables/reference/provenance.sql
-- @include schema/tables/reference/architecture_class.sql
-- @include schema/tables/reference/tensor_role.sql
-- @include schema/tables/reference/script.sql
-- @include schema/tables/reference/block.sql
-- @include schema/tables/reference/break_property.sql
-- @include schema/tables/reference/language.sql
-- @include schema/tables/reference/general_category.sql
-- @include schema/tables/reference/semantic_relation_type.sql
-- @include schema/tables/reference/pos.sql
-- @include schema/tables/reference/deprel.sql
-- @include schema/tables/reference/morph_feature.sql
-- @include schema/tables/reference/lexname.sql
-- @include schema/tables/reference/edge_type.sql
