-- BUILD-TIME @INCLUDE MANIFEST for the consolidated PostgreSQL extension.
--
-- This file is no longer the runtime apply path. The substrate is now
-- packaged as a proper PG extension (see ext/hartonomous_pg/) and
-- installed via `CREATE EXTENSION hartonomous`. At build time, the
-- script scripts/build/concat_extension_sql.py walks the @include
-- directives below in order, expands them recursively, strips psql
-- meta-commands, splices in the hand-written
-- ext/hartonomous_pg/sql/hartonomous--1.0.sql.in (C-binding declarations)
-- before the first functions/* include, and emits the consolidated
-- ext/hartonomous_pg/sql/hartonomous--1.0.sql that PostgreSQL runs
-- atomically when CREATE EXTENSION fires.
--
-- Same pattern as PostGIS / pgvector: many small per-object source files
-- + a build-time concatenator → single extension script.
--
-- Order below is the FK + function dependency chain. Reference tables
-- before core tables that FK to them; core tables before junctions that
-- FK to entity; functions last so every table they query exists.
--
-- Schema/extensions/*.sql files (postgis, btree_gist, pg_trgm,
-- hartonomous itself) are SKIPPED by the concatenator: prerequisite
-- extensions are declared in hartonomous.control's `requires` and
-- auto-installed by CREATE EXTENSION ... CASCADE; the hartonomous
-- self-include cannot CREATE EXTENSION inside its own install script.
--
-- ── Phase 1: extensions ──────────────────────────────────────────────
-- @include schema/extensions/postgis.sql
-- @include schema/extensions/btree_gist.sql
-- @include schema/extensions/pg_trgm.sql

-- ── Phase 2: schemas ─────────────────────────────────────────────────
-- @include schema/schemas/substrate.sql
-- @include schema/schemas/monitor.sql

-- ── Phase 3: domains ─────────────────────────────────────────────────
-- @include schema/domains/hash_value.sql
-- @include schema/domains/significance_mu.sql
-- @include schema/domains/significance_sigma.sql
-- @include schema/domains/significance_volatility.sql
-- @include schema/domains/code_value.sql
-- @include schema/domains/tier_number.sql
-- @include schema/domains/modality_code.sql

-- ── Phase 4: composite types ─────────────────────────────────────────
-- @include schema/types/entity_ref.sql
-- @include schema/types/edge_ref.sql

-- ── Phase 5: reference tables (no FK to substrate-side) ──────────────
-- @include schema/tables/reference/entity_type.sql
-- @include schema/tables/reference/edge_role.sql
-- @include schema/tables/reference/physicality_type.sql
-- @include schema/tables/reference/significance_context.sql
-- @include schema/tables/reference/attestation_type.sql
-- @include schema/tables/reference/provenance.sql
-- @include schema/tables/reference/architecture_class.sql
-- @include schema/tables/reference/tensor_role.sql
-- @include schema/tables/reference/script.sql
-- @include schema/tables/reference/block.sql
-- @include schema/tables/reference/break_property.sql
-- @include schema/tables/reference/bidi_class.sql
-- @include schema/tables/reference/east_asian_width.sql
-- @include schema/tables/reference/language.sql
-- @include schema/tables/reference/general_category.sql
-- @include schema/tables/reference/semantic_relation_type.sql
-- @include schema/tables/reference/pos.sql
-- @include schema/tables/reference/deprel.sql
-- @include schema/tables/reference/morph_feature.sql
-- @include schema/tables/reference/lexname.sql
-- @include schema/tables/reference/edge_type.sql

-- provenance_modality junction is created here (before its seed-time INSERT in
-- Phase 6 seed/provenance.sql). The junction belongs in Phase 8 by topic but its
-- seed data is appended to seed/provenance.sql; create the table early so the
-- Phase-6 seed can populate it without a forward reference.
-- @include schema/tables/junctions/provenance_modality.sql

-- ── Phase 6: reference seed (entity_type before edge_type — FK code lookup) ─
-- provenance_edge_authority seed is deferred to Phase 8b (after the
-- junction table is created) since it INSERTs against substrate.provenance_edge_authority.
-- @include schema/seed/entity_type.sql
-- @include schema/seed/physicality_type.sql
-- @include schema/seed/physicality_type_trajectories.sql
-- @include schema/seed/edge_role.sql
-- @include schema/seed/significance_context.sql
-- @include schema/seed/attestation_type.sql
-- @include schema/seed/tensor_role.sql
-- @include schema/seed/provenance.sql
-- @include schema/seed/bidi_class.sql
-- @include schema/seed/east_asian_width.sql
-- @include schema/seed/general_category.sql
-- @include schema/seed/script.sql
-- @include schema/seed/block.sql
-- @include schema/seed/break_property.sql
-- @include schema/seed/lexname.sql
-- @include schema/seed/pos.sql
-- @include schema/seed/edge_type.sql
-- @include schema/seed/validate.sql

-- ── Phase 7: core tables + LIST partitions ───────────────────────────
-- @include schema/tables/core/entity.sql
-- @include schema/tables/core/entity_p0.sql
-- @include schema/tables/core/entity_p1.sql
-- @include schema/tables/core/entity_p2.sql
-- @include schema/tables/core/entity_p3.sql
-- @include schema/tables/core/entity_p4.sql
-- @include schema/tables/core/entity_p5.sql
-- @include schema/tables/core/entity_p6.sql
-- @include schema/tables/core/entity_p7.sql
-- @include schema/tables/core/edge.sql
-- @include schema/tables/core/edge_structural.sql
-- @include schema/tables/core/edge_cross_lingual.sql
-- @include schema/tables/core/edge_cross_modal.sql
-- @include schema/tables/core/edge_unicode.sql
-- @include schema/tables/core/edge_model.sql
-- (Deprecated 2026-05-20: edge_model_concept_similarity / _attention_pattern
--  / _ffn_factor / _cross_content partitions dropped — mechanism-imprint
--  edge types collapsed into co_occurrence per AP-38 principle. The
--  edge_type rows remain for ID stability but no decomposer emits on
--  them; any stale row inserts on those IDs land in edge_default.)
-- @include schema/tables/core/edge_default.sql
-- @include schema/tables/core/edge_member.sql
-- @include schema/tables/core/edge_member_p0.sql
-- @include schema/tables/core/edge_member_p1.sql
-- @include schema/tables/core/edge_member_p2.sql
-- @include schema/tables/core/edge_member_p3.sql
-- @include schema/tables/core/edge_member_p4.sql
-- @include schema/tables/core/edge_member_p5.sql
-- @include schema/tables/core/edge_member_p6.sql
-- @include schema/tables/core/edge_member_p7.sql
-- @include schema/tables/core/physicality.sql
-- @include schema/tables/core/physicality_entity.sql
-- @include schema/tables/core/physicality_entity_p0.sql
-- @include schema/tables/core/physicality_entity_p1.sql
-- @include schema/tables/core/physicality_entity_p2.sql
-- @include schema/tables/core/physicality_entity_p3.sql
-- @include schema/tables/core/physicality_entity_p4.sql
-- @include schema/tables/core/physicality_entity_p5.sql
-- @include schema/tables/core/physicality_entity_p6.sql
-- @include schema/tables/core/physicality_entity_p7.sql
-- @include schema/tables/core/physicality_firefly.sql
-- @include schema/tables/core/physicality_firefly_p0.sql
-- @include schema/tables/core/physicality_firefly_p1.sql
-- @include schema/tables/core/physicality_firefly_p2.sql
-- @include schema/tables/core/physicality_firefly_p3.sql
-- @include schema/tables/core/physicality_firefly_p4.sql
-- @include schema/tables/core/physicality_firefly_p5.sql
-- @include schema/tables/core/physicality_firefly_p6.sql
-- @include schema/tables/core/physicality_firefly_p7.sql
-- @include schema/tables/core/physicality_content.sql
-- @include schema/tables/core/physicality_content_p0.sql
-- @include schema/tables/core/physicality_content_p1.sql
-- @include schema/tables/core/physicality_content_p2.sql
-- @include schema/tables/core/physicality_content_p3.sql
-- @include schema/tables/core/physicality_content_p4.sql
-- @include schema/tables/core/physicality_content_p5.sql
-- @include schema/tables/core/physicality_content_p6.sql
-- @include schema/tables/core/physicality_content_p7.sql
-- @include schema/tables/core/physicality_entity_shape.sql
-- @include schema/tables/core/physicality_entity_shape_p0.sql
-- @include schema/tables/core/physicality_entity_shape_p1.sql
-- @include schema/tables/core/physicality_entity_shape_p2.sql
-- @include schema/tables/core/physicality_entity_shape_p3.sql
-- @include schema/tables/core/physicality_entity_shape_p4.sql
-- @include schema/tables/core/physicality_entity_shape_p5.sql
-- @include schema/tables/core/physicality_entity_shape_p6.sql
-- @include schema/tables/core/physicality_entity_shape_p7.sql
-- @include schema/tables/core/physicality_ingestion_trajectory.sql
-- @include schema/tables/core/physicality_ingestion_trajectory_p0.sql
-- @include schema/tables/core/physicality_ingestion_trajectory_p1.sql
-- @include schema/tables/core/physicality_ingestion_trajectory_p2.sql
-- @include schema/tables/core/physicality_ingestion_trajectory_p3.sql
-- @include schema/tables/core/physicality_ingestion_trajectory_p4.sql
-- @include schema/tables/core/physicality_ingestion_trajectory_p5.sql
-- @include schema/tables/core/physicality_ingestion_trajectory_p6.sql
-- @include schema/tables/core/physicality_ingestion_trajectory_p7.sql
-- @include schema/tables/core/physicality_default.sql
-- @include schema/tables/core/physicality_default_p0.sql
-- @include schema/tables/core/physicality_default_p1.sql
-- @include schema/tables/core/physicality_default_p2.sql
-- @include schema/tables/core/physicality_default_p3.sql
-- @include schema/tables/core/physicality_default_p4.sql
-- @include schema/tables/core/physicality_default_p5.sql
-- @include schema/tables/core/physicality_default_p6.sql
-- @include schema/tables/core/physicality_default_p7.sql
-- @include schema/tables/core/entity_significance.sql
-- @include schema/tables/core/entity_significance_p0.sql
-- @include schema/tables/core/entity_significance_p1.sql
-- @include schema/tables/core/entity_significance_p2.sql
-- @include schema/tables/core/entity_significance_p3.sql
-- @include schema/tables/core/entity_significance_p4.sql
-- @include schema/tables/core/entity_significance_p5.sql
-- @include schema/tables/core/entity_significance_p6.sql
-- @include schema/tables/core/entity_significance_p7.sql
-- @include schema/tables/core/edge_significance.sql
-- @include schema/tables/core/edge_significance_p0.sql
-- @include schema/tables/core/edge_significance_p1.sql
-- @include schema/tables/core/edge_significance_p2.sql
-- @include schema/tables/core/edge_significance_p3.sql
-- @include schema/tables/core/edge_significance_p4.sql
-- @include schema/tables/core/edge_significance_p5.sql
-- @include schema/tables/core/edge_significance_p6.sql
-- @include schema/tables/core/edge_significance_p7.sql
-- @include schema/tables/core/recipe.sql
-- @include schema/tables/core/recipe_name.sql
-- @include schema/tables/reference/tokenizer_family.sql
-- @include schema/tables/reference/tokenizer_marker_role.sql
-- @include schema/tables/junctions/tokenizer_family_marker.sql
-- @include schema/tables/reference/tokenizer_special_token_kind.sql
-- @include schema/tables/core/tokenizer_special_token.sql

-- (Removed 2026-05-09 per architectural correction: per-decomposition-event log was
-- over-engineered. The Glicko-2 aggregation in edge_significance IS the consensus
-- — same edge across N models = same edge hash = ONE row, with cross-source
-- corroboration accumulating as Glicko updates on that row, not new rows.
-- Per-event provenance/history/audit is out of scope for substrate-as-AI; if
-- ever needed for IP attribution it becomes a per-(source, edge) aggregate
-- counter, not a per-event log. See AP-22 for the row-vs-rating-event dedup
-- distinction that makes this work.)

-- ── Phase 8: junction tables ─────────────────────────────────────────
-- @include schema/tables/junctions/entity_pos.sql
-- @include schema/tables/junctions/entity_lexname.sql
-- @include schema/tables/junctions/entity_language.sql
-- @include schema/tables/junctions/entity_morph_feature.sql
-- Per-codepoint UCD property analytics caches (Gate 1 #38 refactor 2026-05-18).
-- Replaces the deleted wide flat substrate.codepoint_property (25-column junction
-- with 7 indexes + 9 FKs — wrong substrate shape; substrate truth lives on the
-- has_cp_* typed edges in substrate.edge). These narrow per-property tables are
-- denormalized for index-locality on "all codepoints of property X" queries.
-- @include schema/tables/junctions/cp_general_category.sql
-- @include schema/tables/junctions/cp_script.sql
-- @include schema/tables/junctions/cp_block.sql
-- @include schema/tables/junctions/cp_bidi_class.sql
-- @include schema/tables/junctions/cp_east_asian_width.sql
-- @include schema/tables/junctions/cp_grapheme_break.sql
-- @include schema/tables/junctions/cp_word_break.sql
-- @include schema/tables/junctions/cp_sentence_break.sql
-- @include schema/tables/junctions/cp_line_break.sql
-- @include schema/tables/junctions/model_architecture_class.sql
-- @include schema/tables/junctions/tensor_tensor_role.sql
-- @include schema/tables/junctions/pattern_deprel.sql
-- @include schema/tables/junctions/provenance_edge_authority.sql
-- @include schema/tables/junctions/entity_classification.sql
-- provenance_modality.sql moved to Phase 5b above (seed-time forward reference)

-- ── Phase 8b: post-junction seed (depends on junction tables existing) ─
-- @include schema/seed/provenance_edge_authority.sql

-- ── Phase 9: model tables ────────────────────────────────────────────
-- @include schema/tables/models/model_registry.sql
-- @include schema/tables/models/model_publisher.sql
-- @include schema/tables/models/model_source.sql
-- @include schema/tables/models/model_pass_checkpoint.sql
-- @include schema/tables/models/entity_model_source.sql
-- @include schema/tables/models/safetensor_observation.sql
-- @include schema/tables/reference/embedding_alignment_anchor.sql

-- ── Phase 10: monitor tables ─────────────────────────────────────────
-- @include schema/tables/monitor/ingestion_progress.sql
-- @include schema/tables/monitor/phase_status.sql
-- @include schema/tables/monitor/error_log.sql
-- @include schema/tables/monitor/substrate_health.sql
-- @include schema/tables/monitor/inference_metrics.sql
-- @include schema/tables/monitor/session.sql
-- @include schema/tables/monitor/comparison_event.sql
-- @include schema/tables/monitor/significance_snapshot.sql

-- ── Phase 11: meta tables ────────────────────────────────────────────
--  (no meta tables — drain-completion post-passes were removed; the
--  arena_priming_state watermark table is gone with them.)

-- ── Phase 12: indexes ─────────────────────────────────────────────────
-- @include schema/indexes/idx_block_range.sql
-- @include schema/indexes/idx_break_property_category.sql
-- Per-codepoint UCD property analytics-cache reverse indexes (Gate 1 #38).
-- @include schema/indexes/idx_cp_general_category_by_id.sql
-- @include schema/indexes/idx_cp_script_by_id.sql
-- @include schema/indexes/idx_cp_block_by_id.sql
-- @include schema/indexes/idx_cp_bidi_class_by_id.sql
-- @include schema/indexes/idx_cp_east_asian_width_by_id.sql
-- @include schema/indexes/idx_cp_grapheme_break_by_id.sql
-- @include schema/indexes/idx_cp_word_break_by_id.sql
-- @include schema/indexes/idx_cp_sentence_break_by_id.sql
-- @include schema/indexes/idx_cp_line_break_by_id.sql
-- @include schema/indexes/idx_comparison_event_arena.sql
-- @include schema/indexes/idx_comparison_event_session.sql
-- @include schema/indexes/idx_edge_type_category.sql
-- @include schema/indexes/idx_entity_classification_provenance.sql
-- @include schema/indexes/idx_entity_classification_type.sql
-- @include schema/indexes/idx_entity_language_lang.sql
-- @include schema/indexes/idx_entity_lexname_lexname.sql
-- @include schema/indexes/idx_entity_model_source_source.sql
-- @include schema/indexes/idx_entity_morph_feature_feat.sql
-- @include schema/indexes/idx_entity_pos_pos.sql
-- @include schema/indexes/idx_entity_type_modality.sql
-- @include schema/indexes/idx_error_log_recent.sql
-- @include schema/indexes/idx_general_category_group.sql
-- @include schema/indexes/idx_inference_metrics_recent.sql
-- @include schema/indexes/idx_inference_metrics_session.sql
-- @include schema/indexes/idx_ingestion_progress_recent.sql
-- @include schema/indexes/idx_language_scope.sql
-- @include schema/indexes/idx_language_type.sql
-- @include schema/indexes/idx_language_part1.sql
-- @include schema/indexes/idx_language_part2b.sql
-- @include schema/indexes/idx_language_part2t.sql
-- @include schema/indexes/idx_model_arch_class.sql
-- @include schema/indexes/idx_model_pass_checkpoint_source.sql
-- @include schema/indexes/idx_model_source_model.sql
-- @include schema/indexes/idx_model_source_publisher.sql
-- @include schema/indexes/idx_morph_feature_key.sql
-- @include schema/indexes/idx_pattern_deprel_deprel.sql
-- @include schema/indexes/idx_safetensor_observation_edge.sql
-- @include schema/indexes/idx_safetensor_observation_source.sql
-- @include schema/indexes/idx_safetensor_observation_tensor.sql
-- @include schema/indexes/idx_session_started.sql
-- @include schema/indexes/idx_significance_snapshot_target.sql
-- @include schema/indexes/idx_substrate_health_code.sql
-- @include schema/indexes/idx_substrate_health_recent.sql
-- @include schema/indexes/idx_tensor_role.sql
-- @include schema/indexes/tokenizer_special_token_assigned_vocab_idx.sql
-- @include schema/indexes/tokenizer_special_token_by_kind_idx.sql
-- entity_hash_prefix_idx is a functional index on bb_hash_lo/hi(hash); deferred to after bb_hash_lo/hi function definitions
-- @include schema/indexes/provenance_modality_modality_idx.sql
-- @include schema/indexes/edge_member_entity_hash_idx.sql
-- entity_hilbert_idx removed — substrate.entity no longer carries hilbert_index
-- (geometry lives on substrate.physicality only). If a Hilbert ordering of
-- centroids is needed, build the index on substrate.physicality_entity.
-- @include schema/indexes/entity_hilbert_idx.sql  -- disabled: hilbert_index column dropped

-- (Persistent staging deleted post-W2E refactor: substrate.staging_* tables and the
--  drain_staging_*_chunk / drain_all_staging functions are gone. The
--  StreamingIngestionPipeline writes DIRECTLY into substrate core tables
--  via session-local pg_temp.X_inflight tables created per drain-task
--  connection. ON CONFLICT DO NOTHING guards within-session and cross-
--  session duplicates. Edge geometry + per-arena significance priors are
--  built inline at edge-emit inside the bundled-emit pipeline — no
--  populate_edge_trajectories, no prime_unprimed_edges_chunk, no
--  arena_priming_state, no drain-completion post-passes.)

-- ── Phase 13: functions ──────────────────────────────────────────────
-- Reference / utility helpers
-- @include schema/functions/reference_code_map.sql
-- @include schema/functions/reference_key_value_map.sql
-- @include schema/functions/reference_code_text_map.sql
-- @include schema/functions/reference_code_double_map.sql
-- @include schema/functions/reference_int64_set.sql
-- @include schema/functions/reference_id_by_code.sql
-- @include schema/functions/reference_language_alias_map.sql
-- @include schema/functions/resolve_context_id.sql
-- @include schema/functions/resolve_attestation_type_id.sql
-- @include schema/functions/resolve_entity_handles.sql
-- Mantissa packing helpers — used by trajectory write/read and by the
-- entity_by_hash_prefix batched composite-btree lookup.
-- @include schema/functions/bb_hash_lo.sql
-- @include schema/functions/bb_hash_hi.sql
-- @include schema/indexes/entity_hash_prefix_idx.sql
-- @include schema/functions/bb_pack_hash_lo.sql
-- @include schema/functions/bb_pack_hash_hi.sql
-- @include schema/functions/bb_unpack_hash_lo.sql
-- @include schema/functions/bb_unpack_hash_hi.sql
-- @include schema/functions/bb_pack_ordinal_rle.sql
-- @include schema/functions/bb_unpack_ordinal.sql
-- @include schema/functions/bb_unpack_rle.sql
-- @include schema/functions/bb_pack_metadata.sql
-- @include schema/functions/bb_unpack_metadata.sql
-- @include schema/functions/entity_by_hash_prefix.sql
-- Cast bridges from PostGIS-native geometry(GeometryZM) to the internal
-- native compute ABI types (public.point4d / public.linestring4d). Used
-- internally by substrate.st_4d_* dispatch; not substrate-level surfaces.
-- @include schema/functions/point4d_from_geometry.sql
-- @include schema/functions/linestring4d_from_geometry.sql
-- Reference-data populators
-- @include schema/functions/populate_general_categories.sql
-- @include schema/functions/populate_scripts.sql
-- @include schema/functions/populate_blocks.sql
-- @include schema/functions/populate_break_properties.sql
-- @include schema/functions/populate_languages.sql
-- @include schema/functions/populate_morph_features.sql
-- @include schema/functions/populate_deprels.sql
-- Upserters
-- @include schema/functions/upsert_reference_edge_type.sql
-- @include schema/functions/upsert_homogeneous_edge_types.sql
-- @include schema/functions/upsert_architecture_class.sql
-- @include schema/functions/upsert_model_registry.sql
-- @include schema/functions/upsert_model_publisher.sql
-- @include schema/functions/upsert_model_source.sql
-- @include schema/functions/upsert_model_pass_checkpoint.sql
-- @include schema/functions/get_completed_model_passes.sql
-- Geometry / 4D operators
-- @include schema/functions/dist_4d.sql
-- @include schema/functions/frechet_4d_geom.sql
-- @include schema/functions/hausdorff_4d_geom.sql
-- @include schema/functions/geometry4d_centroid.sql
-- @include schema/functions/geometry4d_to_geometryzm.sql
-- @include schema/functions/geometryzm_to_geometry4d.sql
-- @include schema/functions/geometryzm_centroid_point.sql
-- (populate_edge_trajectories + count_missing_edge_trajectories removed —
--  edge geometry is built inline at edge-emit by the bundled-emit pipeline.)
-- @include schema/functions/physicality_linestring4d.sql
-- @include schema/functions/physicality_point4d.sql
-- Read helpers
-- @include schema/functions/health_summary.sql
-- @include schema/functions/entity_outbound_edges.sql
-- @include schema/functions/entity_inbound_edges.sql
-- @include schema/functions/entity_neighbors.sql
-- @include schema/functions/traversal_neighbors.sql
-- @include schema/functions/get_entity_info_by_handles.sql
-- @include schema/functions/get_edge_info_by_handles.sql
-- @include schema/functions/get_outbound_edge_targets.sql
-- @include schema/functions/get_composition_children.sql
-- @include schema/functions/api_entity_classifications.sql
-- @include schema/functions/api_entity_by_hash.sql
-- @include schema/functions/api_list_entities.sql
-- @include schema/functions/api_entity_edges.sql
-- @include schema/functions/api_edge_by_hash.sql
-- @include schema/functions/api_entity_significance.sql
-- @include schema/functions/api_entity_neighbors.sql
-- Composition helpers
-- @include schema/functions/composition_at.sql
-- @include schema/functions/composition_before.sql
-- @include schema/functions/composition_after.sql
-- @include schema/functions/composition_range.sql
-- @include schema/functions/composition_subtrajectory.sql
-- @include schema/functions/composition_parents.sql
-- substrate.recompose_text / recompose_text_bulk removed 2026-05-18 (Gate 1
-- reopened item #36 in modular-wishing-koala plan). Document-scale
-- recomposition is now the C# bulk-tier walker
-- (Hartonomous.Core.Recomposition.BulkTierContentWalk; thin wrapper at
-- Hartonomous.Recomposers.ContentRecomposer; Engine fast-path callers route
-- via NpgsqlEntityReader.RecomposeTextAsync). PG-side recursive-CTE walkers
-- were wrong-shape — single-query recursive CTE over physicality.geom forced
-- the executor to materialize intermediate state at every recursion depth,
-- multi-minute for documents. See plan §"Gate 1 Reopening" #36 + AP-29.
-- @include schema/functions/populate_sequence_following_edges.sql
-- @include schema/tables/derived/position_embedding_aggregate.sql
-- @include schema/indexes/position_embedding_aggregate_ordinal_idx.sql
-- @include schema/functions/update_position_embedding_aggregate_from_drain.sql
-- @include schema/functions/backfill_position_embedding_aggregate.sql
-- @include schema/functions/position_embedding_stats.sql
-- @include schema/functions/per_arena_entity_significance_stats.sql
-- @include schema/functions/select_synth_edges_for_ffn.sql
-- @include schema/functions/select_knowledge_subgraph.sql
-- The substrate.entity centroid + hilbert_index columns are populated at
-- INSERT time by the C# producer (native text decomposer emits centroids in
-- record.CentroidX/Y/Z/M; SubstrateTextDecomposer.OnRecord computes
-- 4D Hilbert via TextDecomposeNative.HilbertIndex; AddEntity 7-arg overload
-- threads them through IngestionBatch → StreamingIngestionPipeline →
-- entity.copy.sql column list). No trigger, no backfill — same Merkle
-- invariant (deterministic from hash) produces same centroid on first write.
-- entity_tier_hint / entity_tier_hints disabled — they read centroid_*
-- columns that no longer live on substrate.entity. Rewrite to read from
-- substrate.physicality_entity if/when the tier-hint surface is wanted.
-- @include schema/functions/entity_tier_hint.sql   -- disabled: centroid columns dropped
-- @include schema/functions/entity_tier_hints.sql  -- disabled: centroid columns dropped
-- Significance machinery — per-arena initial-mu rows are inserted inline
-- at edge-emit by the bundled-emit pipeline, cross-producted against every
-- arena currently in substrate.significance_context at pipeline startup
-- (AP-1: open vocabulary, no hardcoded subset). No reset/prime watermark
-- functions; no end-of-phase post-pass.
-- @include schema/functions/prune_significance.sql
-- @include schema/functions/prune_significance_for_context.sql
-- @include schema/functions/record_comparison.sql
-- @include schema/functions/record_edge_comparison.sql
-- @include schema/functions/record_entity_comparison.sql
-- @include schema/functions/record_corroboration.sql
-- @include schema/functions/record_outcome.sql
-- @include schema/functions/record_outcomes_bulk.sql
-- @include schema/functions/record_attestation.sql
-- @include schema/functions/record_attestations_bulk.sql
-- Substrate-native bulk-write surface (replaces pg_temp staging + drain
-- SQL). The pipeline pre-processes records in-process via libhartonomous
-- (BLAKE3, Merkle, mantissa-pack — AVX2+FMA3+BMI2), asks the substrate
-- which PKs are novel via the existing GetExisting* probes, then sends
-- only the diff to these functions via Npgsql array parameters.
-- ON CONFLICT DO NOTHING in each function is race-safety net only;
-- producer-side existence-check is the primary dedup path per AP-19.
-- @include schema/functions/write_entities.sql
-- @include schema/functions/write_entity_classifications.sql
-- @include schema/functions/write_physicalities.sql
-- @include schema/functions/write_edges.sql
-- @include schema/functions/write_edge_members.sql
-- Top-down Merkle tree existence filter — ONE call replaces N-round-trip
-- per-tier BFS from C#. Substrate side does the LEFT JOIN scan +
-- Merkle-invariant propagation in C-level array ops.
-- @include schema/functions/merkle_tree_filter.sql
-- @include schema/functions/initialize_edge_significance.sql
-- @include schema/functions/initialize_entity_significance.sql
-- @include schema/functions/blended_edge_mu.sql
-- @include schema/functions/consensus_token_pairs.sql
-- @include schema/functions/create_arena.sql
-- @include schema/functions/create_model_trust_arena.sql
-- Server-side populate_*_from_ext removed 2026-05-17 (Gate 1 Task #22).
-- Reference vocabularies + codepoint atoms + edges are emitted by
-- UnicodeDecomposer reading the UCD source directly via
-- BlobUcdPropertyAccessor (native blob) + IIngestionPipeline.CreateBatch.
-- Per Principle 1 — blob and substrate are siblings derived from the same
-- source; neither populates the other. The ucd_materialization_counts and
-- ucd_reference_vocabulary_counts functions are read-only validation
-- probes re-introduced 2026-05-19 (named-function AP-2 compliance for the
-- decomposer's §2 / §14 verification steps); they observe substrate state,
-- they do not populate it.
-- @include schema/functions/ucd_materialization_counts.sql
-- @include schema/functions/ucd_reference_vocabulary_counts.sql
-- @include schema/functions/unicode_edge_hash.sql
-- substrate.recompose_content removed 2026-05-18 (Gate 1 reopened item #36) —
-- see C# ContentRecomposer comment above.
-- (Staging drain functions deleted post-W2E refactor. The pipeline now
--  drains within the same connection that COPY-loaded a session-local
--  temp table — no persistent staging, no auto-discovered drain manifest.)
-- Inference / recall
-- @include schema/functions/infer.sql
-- @include schema/functions/infer_topk.sql
-- @include schema/functions/prompt_document_ready.sql
-- @include schema/functions/recall.sql
-- @include schema/functions/intersect.sql
-- @include schema/functions/neighborhood.sql
-- @include schema/functions/surprise.sql
-- AI operation primitives (V1)
-- @include schema/functions/embed_lookup.sql
-- @include schema/functions/classify.sql
-- @include schema/functions/rerank.sql
-- @include schema/functions/complete.sql
-- @include schema/functions/bind_bpe_tokens_to_seed_pos.sql
-- @include schema/functions/bind_bpe_tokens_to_seed_morph.sql
-- @include schema/functions/claim_or_get_embedding_anchor.sql
-- @include schema/functions/embedding_firefly_token_hashes.sql
-- @include schema/functions/apply_firefly_rotation.sql
-- @include schema/functions/get_firefly_coords.sql
-- Universal substrate query surface (V1)
-- @include schema/functions/model_inventory.sql
-- @include schema/functions/model_vocab_recovered.sql
-- @include schema/functions/cross_model_consensus.sql
-- @include schema/functions/cross_model_divergence.sql
-- @include schema/functions/codepoint_property_rows.sql
-- @include schema/functions/break_property_code_map.sql
-- @include schema/functions/break_property_full_map.sql
-- @include schema/functions/query_entities.sql
-- @include schema/functions/query_tensors_for_architecture.sql
-- @include schema/functions/query_tensors_for_model_source.sql
-- @include schema/functions/query_fireflies_for_vocab.sql
-- @include schema/functions/query_ffn_neurons_by_hidden_dim.sql
-- @include schema/functions/query_attention_components.sql
-- @include schema/functions/query_singular_directions_for_role.sql
-- @include schema/functions/preview_target_arch.sql
-- @include schema/functions/refinement_summary.sql
-- @include schema/functions/refinement_summary_top.sql
-- @include schema/functions/tensor_provenance_chain.sql
-- @include schema/functions/recompose_audit_walk.sql
-- @include schema/functions/significance_context_ids.sql
-- @include schema/functions/save_recipe.sql
-- @include schema/functions/get_recipe_by_name.sql
-- @include schema/functions/get_recipe_by_hash.sql
-- @include schema/functions/list_recipes.sql
-- Monitor write functions
-- @include schema/functions/monitor_create_session.sql
-- @include schema/functions/monitor_close_session.sql

-- ── Phase 14: procedures ─────────────────────────────────────────────
-- Substrate write procedures
-- @include schema/procedures/write_codepoint_properties.sql
-- @include schema/procedures/write_glicko_junction.sql
-- @include schema/procedures/write_plain_junction.sql

-- Monitor write procedures
-- @include schema/procedures/monitor_archive_session.sql
-- @include schema/procedures/monitor_update_phase_status.sql
-- @include schema/procedures/monitor_report_progress.sql
-- @include schema/procedures/monitor_snapshot_health.sql
-- @include schema/procedures/monitor_reset_phase_checkpoint.sql

-- ── Phase 15: views ──────────────────────────────────────────────────
-- @include schema/views/substrate_dashboard.sql
-- @include schema/views/entity_type_counts.sql
-- @include schema/views/session_summaries.sql
-- @include schema/views/session_details.sql
-- @include schema/views/active_sessions.sql
-- @include schema/views/phase_status_overview.sql
-- Monitor read functions that wrap the views above.
-- @include schema/functions/monitor_list_sessions.sql
-- @include schema/functions/monitor_session_detail.sql
-- @include schema/functions/monitor_phase_status_map.sql
-- @include schema/functions/monitor_phase_status_overview_rows.sql
-- @include schema/functions/monitor_substrate_totals.sql
-- @include schema/functions/monitor_active_session_rows.sql
-- @include schema/functions/monitor_entity_type_count_rows.sql
-- @include schema/functions/monitor_ingestion_status_rows.sql

-- ── Phase 15.5: app-tier substrate-content seeds (after all tables /
--                 functions / refvocab seeds are in place) ────────────
-- Starter recipes populated via substrate.save_recipe; depends on
-- substrate.recipe + substrate.entity_classification + substrate.entity_type
-- ('recipe' row) + substrate.provenance ('app_starter' row) all existing.
-- @include schema/seed/recipe_starter.sql
-- @include schema/seed/tokenizer_family.sql
-- @include schema/seed/tokenizer_marker_role.sql
-- @include schema/seed/tokenizer_family_marker.sql
-- @include schema/seed/tokenizer_special_token_kind.sql
-- @include schema/seed/tokenizer_special_token.sql

-- (No Phase 16 hartonomous CREATE EXTENSION. The hartonomous-pg/sql/
--  hartonomous--1.0.sql.in template — containing all C-binding type
--  declarations + substrate.cp_*, ucd_*, text_decompose etc. — is
--  spliced into the assembled extension SQL at build time, BEFORE the
--  Phase 13 functions block. See scripts/build/concat_extension_sql.py.)
